---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
permissions: # added using https://github.com/step-security/secure-workflows
  contents: read
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run tests
        run: make test
  e2e-test:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: k3s-cel-approver-policy-plugin
      IMG: registry.dummy-domain.com/cert-manager-cel-approver-policy-plugin:dev
      IMG_FILE: cel-approver-policy-plugin-image.tar
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          outputs: type=docker,dest=${{ env.IMG_FILE }}
          tags: ${{ env.IMG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: ${{ env.CLUSTER_NAME }}
      - run: |
          kubectl cluster-info
          kubectl version --output=yaml
          helm version
      - run: |
          k3d image import ${{ env.IMG_FILE }} --cluster ${{ env.CLUSTER_NAME }}
          helm repo add jetstack https://charts.jetstack.io
          helm upgrade cert-manager jetstack/cert-manager \
            --install \
            --create-namespace \
            --namespace cert-manager \
            --set installCRDs=true \
            --set extraArgs={--controllers='*\,-certificaterequests-approver'} # Disable cert-manager's built-in approver \
            --wait
          helm upgrade cert-manager-approver-policy jetstack/cert-manager-approver-policy |
            --install \
            --namespace cert-manager \
            --set image.repository=${{ env.IMG }} \
            --wait
