---
name: CI
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
permissions: # added using https://github.com/step-security/secure-workflows
  contents: read
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout 5m
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Run tests
        run: make test
  e2e-test:
    runs-on: ubuntu-latest
    env:
      IMG: registry.dummy-domain.com/cert-manager-cel-approver-policy-plugin:dev
      IMG_FILE: cel-approver-policy-plugin-image.tar
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          outputs: type=docker,dest=${{ env.IMG_FILE }}
          tags: ${{ env.IMG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: AbsaOSS/k3d-action@v2
      - run: |
          kubectl cluster-info
          kubectl version --output=yaml
      - run: |
          k3d image import ${{ env.IMG_FILE }}
          helm version
